/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProyP;

import hospital.gestPersonal;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Paul_
 */
public class VtaMaain extends javax.swing.JFrame {
    /**
     * Creates new form VtaMain
     */
    grafoPacientes listaPacientes = new grafoPacientes();
    Lista citas = new Lista();
    public VtaMaain() {
        initComponents();
        cargarDatosPrueba();      
        cargarTablaMain();
    }
      
    // Método para cargar datos iniciales
    public void cargarDatosPrueba() {
        
        //Nombre y Apellido
        listaPacientes.insertLast("HW-001", "Juan", "Pérez");
        listaPacientes.insertLast("HW-002","Ana", "López");
        
        // Agregarle una cita de prueba a Juan
        Paciente juan = listaPacientes.buscar("HW-001");
        Cita prueba = new Cita("Juan", "Pérez", "10:00", "01/12/2023", "Dolor de cabeza");
        prueba.setFolio("C-001");
        juan.incrementarCitas(prueba);
        citas.insertLast(prueba.getNombre(), prueba.getApellidos(), prueba.getAsunto(), prueba.getHora(), prueba.getFecha());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        removeBttn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        newCitaBttn = new javax.swing.JButton();
        txtBuscarPaciente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnBuscar = new javax.swing.JButton();
        gestPersonal = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        gestPacientesBttn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHistorialCitas = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("Centro Medico \"Las 3 Torres\"");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 430, 40));

        removeBttn.setText("Eliminar Cita");
        removeBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBttnActionPerformed(evt);
            }
        });
        jPanel1.add(removeBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 100, 50));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setText("Citas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel4.setText("Personal");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        newCitaBttn.setText("Agregar Cita");
        newCitaBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCitaBttnActionPerformed(evt);
            }
        });
        jPanel1.add(newCitaBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 100, 50));

        txtBuscarPaciente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtBuscarPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtBuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtBuscarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 280, 30));

        jLabel3.setFont(new java.awt.Font("Arial Black", 2, 16)); // NOI18N
        jLabel3.setText("Busqueda por expediente");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 230, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Historial de citas");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 200, 840, 10));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 80, 30));

        gestPersonal.setText("Gestionar Personal");
        gestPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestPersonalActionPerformed(evt);
            }
        });
        jPanel1.add(gestPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 140, 50));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel6.setText("Pacientes");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, -1, -1));

        gestPacientesBttn.setText("Gestionar Pacientes");
        gestPacientesBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestPacientesBttnActionPerformed(evt);
            }
        });
        jPanel1.add(gestPacientesBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, 140, 50));

        tblHistorialCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Folio", "Nombre", "Apellido", "Fecha", "Hora", "Asunto", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblHistorialCitas);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 830, 240));

        jLabel7.setText("(Puede ver el expediente en gestionar pacientes)");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarPacienteActionPerformed

    private void newCitaBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCitaBttnActionPerformed
        VtanewCita dialog=new VtanewCita(this, true, this);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        cargarTablaMain();
        
    }//GEN-LAST:event_newCitaBttnActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String buscado = txtBuscarPaciente.getText().trim();

        if (buscado.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Escribe un expediente.");
            return;
        }
      
        Paciente encontrado = listaPacientes.buscar(buscado);

        if (encontrado != null) {
            //  Si lo encontramos, llenamos la tabla con sus citas
            llenarTabla(encontrado);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Paciente no encontrado.");
            cargarTablaMain();
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void gestPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestPersonalActionPerformed
        gestPersonal vta=new gestPersonal(this, true);
        vta.setVisible(true);
    }//GEN-LAST:event_gestPersonalActionPerformed

    private void removeBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBttnActionPerformed
        if(tblHistorialCitas.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(null, "Ningun elemento fue seleccionado", "ADVERTENCIA",
            JOptionPane.WARNING_MESSAGE);
            return;
        }
        String folio = tblHistorialCitas.getValueAt(tblHistorialCitas.getSelectedRow(), 0).toString();
        
        // Eliminar del grafo
        citas.eliminarX(folio);
        eliminarCitaDePaciente(folio);
        
        JOptionPane.showMessageDialog(this,
            "Paciente eliminado exitosamente",
            "Éxito",
            JOptionPane.INFORMATION_MESSAGE);
               
        cargarTablaMain();
    }//GEN-LAST:event_removeBttnActionPerformed

    private void gestPacientesBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestPacientesBttnActionPerformed
        VtaPacientes dial=new VtaPacientes(this, true,listaPacientes);
        dial.setLocationRelativeTo(this);
        dial.setVisible(true);
    }//GEN-LAST:event_gestPacientesBttnActionPerformed
    
        //llenar la tabla con citas del paciente buscado
    public void llenarTabla(Paciente paciente) {
        DefaultTableModel modelo = (DefaultTableModel) tblHistorialCitas.getModel();
        modelo.setRowCount(0);
        
        // Obtener las citas del paciente
        Cita[] citas = paciente.getListaCitas();
        
        // Recorrer el arreglo y llenar el modelo
        if (citas != null) {
            for (Cita c : citas) {
                // Validamos que la cita no sea nula 
                if (c != null) {
                    Object[] fila = {
                        c.getFolio() != null ? c.getFolio() : "S/N", 
                        c.getNombre(),
                        c.getApellidos(),
                        c.getFecha(),
                        c.getHora(),
                        c.getAsunto(),
                        c.isEstadoCita() ? "Activa" : "Cancelada"
                    };
                    modelo.addRow(fila);
                }
            }
        }
       
        tblHistorialCitas.setModel(modelo);
    }
    
    private void cargarTablaMain() {
        DefaultTableModel modelo = (DefaultTableModel) tblHistorialCitas.getModel();

        modelo.setRowCount(0);
        Paciente actual = listaPacientes.cab; 

        while (actual != null) {
            Cita[] citas = actual.getListaCitas();

            if (citas != null) {
                //tomar cita de cada paciente
                for (Cita cita : citas) {
                    if (cita != null) {
                        // Agregar a la tabla
                        modelo.addRow(new Object[] {
                            cita.getFolio(),
                            cita.getNombre(),
                            cita.getApellidos(),
                            cita.getFecha(),
                            cita.getHora(),
                            cita.getAsunto(),
                            cita.isEstadoCita() ? "Activa" : "Cancelada"
                        });
                    }
                }
            }

            actual = actual.getLigaD();
        }
    }
    
    public Paciente buscarPaciente(String nombre, String apellidos) {
        Paciente actual = listaPacientes.cab;

        while (actual != null) {
            if (actual.getNombre().equalsIgnoreCase(nombre) && 
                actual.getApellidos().equalsIgnoreCase(apellidos)) {
                return actual;
            }
            actual = actual.getLigaD();
        }
        return null;
    }
    
    public void crearPaciente(String expediente, String nombre, String apellidos) {
        listaPacientes.insertLast(expediente, nombre, apellidos);
    }
    
    private void sacarCitas(Paciente paciente) {
        Cita[] citasActuales = paciente.getListaCitas();
        if (citasActuales == null) return;
        
        int contador = 0;
        for (Cita c : citasActuales) {
            if (c != null) {
                contador++;
            }
        }
        
        Cita[] citasNuevas = new Cita[contador];
        int index = 0;
        for (Cita c : citasActuales) {
            if (c != null) {
                citasNuevas[index++] = c;
            }
        }
        
        paciente.setListaCitas(citasNuevas);
    }
    
    private void eliminarCitaDePaciente(String folio) {
        Paciente actual = listaPacientes.cab;
        
        while (actual != null) {
            Cita[] citas = actual.getListaCitas();
            
            if (citas != null) {
                for (int i = 0; i < citas.length; i++) {
                    if (citas[i] != null && citas[i].getFolio() != null 
                        && citas[i].getFolio().equals(folio)) {
                        
                        citas[i] = null;
                        sacarCitas(actual);
                        return;
                    }
                }
            }
            
            actual = actual.getLigaD();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtaMaain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtaMaain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtaMaain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtaMaain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtaMaain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton gestPacientesBttn;
    private javax.swing.JButton gestPersonal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton newCitaBttn;
    private javax.swing.JButton removeBttn;
    private javax.swing.JTable tblHistorialCitas;
    private javax.swing.JTextField txtBuscarPaciente;
    // End of variables declaration//GEN-END:variables
}
